[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Elijah Tarr <elijahotarr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
otest-oriont = "0.0.2"

[tool.poetry.scripts]
test = "tests.test:main"
